language: node_js
node_js:
- '6'
before_install:
- npm install -g phantomjs
deploy:
  provider: npm
  email: saivarunk@gmail.com
  api_key:
    secure: Zjx6aZiF1Zk+b7oquTgYYg4fZELCRq0PuqK3JW0vkfnZ2QjTygKQk7BLB+OnKxSkXzWdR0bKpnjMj00F3xBvdEWBkKas7s/0A3gFZwn5pgBfMPz9Hv80G/HJfb7ECnhf3VZQNevsbnzuvpF5+OvD2fFEgOOxNmGJsb9XWWshC/fVczyfGt5pWtdZFiflTv3vG8xgD09JqDpxfFBRJAdGqq9jN0B1E0rKeTClDW84JV7+K6x/CXP+5XAvwQb8cLvWLjgsMcWd6g+bWL5KQQiyW7Ngc1qEgRp9vVjqhIQbH+hupJhX39YOaF4qtDQ/sA7/VVcv2hYV/9sRnV52hD16AZ/lRjeSzqygzhjFADdJ8Sa/us4fdfCWNEMDGkPpZ74B/3atGChxyCrpmUDAO7yEaxXvW4OM4Kj27OVDAJmyW7jBy4JnXSMfQMIJK0Q7HFFcIW34eryB+1wm8fWxRXFhHbZFAneGO6DXs1+6Gr/ZhBazOWWxNJ7PiXvdwKtNqT+zeOnDPzc3erC0Cf/HytmqSdLi1Ps3gcn0J5x/QbrIGAH7unhD4MIVMOdzFQBUfph8taA4yFOlPZ2CbmOLi+IJwftZC9eV9hjPf1a4EwLpZejjwmoFMudMsIR6L06lXlY3eemagzkYJ7uACP+aWqjv46RIkZ31mQdyOGP2z2sfBp0=
  on:
    tags: false
    repo: saivarunk/vue-toastr-2
